name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: upgrade g++
      run: sudo apt-get -y install g++
    - name: g++ version
      run: g++ --version
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
