name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependancies
      run: sudo apt install libsfml-dev
    - name: make
      run: make
      env:
        CC: gcc-10
        CXX: g++-10
    - name: make check
      run: make check
      env:
        CC: gcc-10
        CXX: g++-10
    - name: make distcheck
      run: make distcheck
      env:
        CC: gcc-10
        CXX: g++-10
